language: python
env:
- TOXENV=py35
- TOXENV=py34
- TOXENV=py33
- TOXENV=py27
- TOXENV=py26
- TOXENV=pypy
install: pip install -U tox
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: johannesgj
  password:
    secure: OM/I051rNSnFm5g8vWp7DOYKBf5n2q23S9QJ2HVtF3N3StibFya5TN/1yresL+wXhROuFUPi2Dxc67LjZyVoOM/POPIMKq2t0K5zInw+teBZJzEv/MozEwxBvFh1LGhLjmxaRfNmwWHbIFpVZGT3Qn0WV8UnxWSz1w8EI7HA7spLE4rw3eJgU0f6Ok7iet+gVWuumKy0UngR5oHU+pT4P3DZfTnm4tdmHvm9iPka5JIHCJBFjHvLY/Na362akveAA/OrpZVqnpwWErHw2ThKLOVqC9hBg7CbmSZY4rh7AVHKxg0ug5YIdFKScTUARyKOXOo9oplQ8tVnoDpBGRCnIQ9C6TlkOti/DXEaPWSdzo/O/ykw+IeoDjwOLVcN4ltLoQRXyMENBAT3cY5AJSp2cO2sImXJnvxhiVleMQm7j3x+Z8fzPAQeJTeMhO5UePixGwJWYNIpQuJbNGsDhADVhfC0Uwg7Vwn99vY4VCWq1NUNLTRhpjl7q2FPbtJCSiB4P2Cap4Pk450vqEdWxqRT9qbO3mbVkzptD3A3mhv6WGHegn2fnFzN/Q30A4YEQK2N46cj3mbgOx+Ga1Z42Uo6HnUa6SEx28xKouoHxTVEXLLkFNw6aKv9p2UgS7ldDHYbz8M93UYSxHzmK43TVF0MrSh13rRSh0wcgH9XSmkJKAg=
  on:
    tags: true
    repo: sloev/pycorm
    condition: $TOXENV == py27
