language: python
env:
- TOXENV=py35
- TOXENV=py34
- TOXENV=py33
- TOXENV=py27
- TOXENV=py26
- TOXENV=pypy
install: pip install -U tox
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: johannesgj
  password:
    secure: yyjLCy6Iaw/4h9lu9CkIdBI4f/vYjqeDGWlAxUUvUv82yGXVU2mnkp5d9w343NmyUbe4tACTOwOAOtX04fhYc1X9mZPHwY8wsTvmVK/c0/fvk1L2HGKJ9Rx9BH/6DEsZVt+HkxXcSatekCVaVFNi8HGLZXcPn5cG++4EIPrRLL0RXh52ljJJMCIsjlGKHJE75gGUMGOhNZpfZQmOOxwYYxQdDgRC6zP7dEjo28YgNRkAyI0QJAycti226fDyHiE9YS7WOwtRUw5PpldcbOTMJ8waVQm4ESs2dumS8W+bPtom6omqJf7p/PY4yT6uXetX1mBvlPYcm1VSooKfUPsvQuwLKRI4gth5USbtkJ+GaE8sixzeojlSh5G3Cf+OXmblnu2UO6xgRQMUnytnuvjNAcVcfHAa6pgB7hSd9lkrs6RIHTBGNS8B6XsqXekqdD5qj4woPTozQm6wlzk40SokmQgKNp/COTovljUR66ns6WAsEea1qBJ+t/nUbO1K5vjJgEmDzPwroONokT2COiHNiQqsBgatwaBszvxWsfrUuhFXLwW0JnOP/tglE2Mk0ht8PkZ+3y4FOmeF2P0T/oeZ8L5ab5rGP1OloM5rqQ0Hkn7fuZduO/bX9mSL8p57VOGxLaF1SeekeAiHOhFCuNfbCp/fH8VqJPesn36eWlLiTcM=
  on:
    tags: true
    repo: sloev/pycorm
    condition: $TOXENV == py27
